stages:
  - build
  - security_scan
  - sign

variables:
  # Using GitLab's built-in registry
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
build_os:
  stage: build
  image: quay.io/podman/stable
  script:
    # Login to Red Hat Registry first
    - podman login -u "$RH_REGISTRY_USER" -p "$RH_REGISTRY_PASSWORD" registry.redhat.io
    # Login to your local GitLab registry so you can push
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Now the build will work
    - podman build -t $IMAGE_TAG .
    - podman push $IMAGE_TAG
compliance_scan:
  stage: security_scan
  image: quay.io/podman/stable
  script:
    - podman pull $IMAGE_TAG
    # Run OpenSCAP to check against PCI-DSS profile
    - podman run --rm $IMAGE_TAG oscap-chroot / /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml --profile pci-dss --report report.html
  artifacts:
    paths:
      - report.html
    expire_in: 1 week

sign_os_image:
  stage: sign
  image:
    name: gcr.io/projectsigstore/cosign:latest
    entrypoint: [""]
  script:
    - echo "$COSIGN_KEY" > cosign.key
    - cosign sign --key cosign.key --tlog-upload=false $IMAGE_TAG
  only:
    - main